{"metadata":{"role":"symbol","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","roleHeading":"Case","title":"ParseError.internalError(_:)","modules":[{"name":"GnustoEngine"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"variants":[{"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","title":"ParseError","navigatorTitle":[{"kind":"identifier","text":"ParseError"}],"kind":"symbol","abstract":[{"text":"Enumerates errors that can occur during the command parsing phase.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ParseError","kind":"identifier"}],"url":"\/documentation\/gnustoengine\/parseerror","role":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","title":"ParseError.internalError(_:)","abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"role":"symbol","url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","type":"topic","url":"\/documentation\/gnustoengine","abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","title":"GnustoEngine","kind":"symbol"}}}