{"variants":[{"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"metadata":{"roleHeading":"Case","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","modules":[{"name":"GnustoEngine"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"ParseError.internalError(_:)","symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"sections":[],"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"title":"GnustoEngine","abstract":[],"type":"topic","url":"\/documentation\/gnustoengine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","kind":"symbol","role":"collection"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}],"url":"\/documentation\/gnustoengine\/parseerror","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ParseError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ParseError","kind":"identifier"}],"role":"symbol","title":"ParseError"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","title":"ParseError.internalError(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","role":"symbol","type":"topic"}}}