{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"metadata":{"title":"ParseError.internalError(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"case","modules":[{"name":"GnustoEngine"}],"roleHeading":"Case","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF"},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","abstract":[],"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","url":"\/documentation\/gnustoengine","kind":"symbol","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","title":"ParseError.internalError(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}]},"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"url":"\/documentation\/gnustoengine\/parseerror","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ParseError"}],"navigatorTitle":[{"kind":"identifier","text":"ParseError"}],"title":"ParseError"}}}