{"sections":[],"abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"]}],"metadata":{"title":"ParseError.internalError(_:)","role":"symbol","symbolKind":"case","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Case","modules":[{"name":"GnustoEngine"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","title":"GnustoEngine","abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","url":"\/documentation\/gnustoengine","type":"topic","kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"abstract":[{"text":"Enumerates errors that can occur during the command parsing phase.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ParseError"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ParseError","kind":"identifier"}],"url":"\/documentation\/gnustoengine\/parseerror","kind":"symbol","type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","title":"ParseError","role":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"title":"ParseError.internalError(_:)","type":"topic","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","role":"symbol","kind":"symbol"}}}