{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["macOS"]}]}],"kind":"symbol","metadata":{"roleHeading":"Case","title":"ActionResponse.internalEngineError(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","modules":[{"name":"GnustoEngine"}],"symbolKind":"case"},"abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"String","type":"codeVoice"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"variants":[{"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","title":"ActionResponse","type":"topic","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionResponse"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"url":"\/documentation\/gnustoengine\/actionresponse"},"doc://GnustoEngine/documentation/GnustoEngine":{"abstract":[],"kind":"symbol","role":"collection","url":"\/documentation\/gnustoengine","title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","role":"symbol","title":"ActionResponse.internalEngineError(_:)","kind":"symbol","type":"topic"}}}