{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"metadata":{"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"GnustoEngine"}],"title":"ActionResponse.internalEngineError(_:)","role":"symbol"},"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","role":"collection","url":"\/documentation\/gnustoengine","kind":"symbol","type":"topic","title":"GnustoEngine"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"kind":"symbol","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","role":"symbol","type":"topic","title":"ActionResponse.internalEngineError(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"String","type":"codeVoice"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"title":"ActionResponse","type":"topic","url":"\/documentation\/gnustoengine\/actionresponse","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionResponse"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","role":"symbol","navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}]}}}