{"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Case","title":"ActionResponse.internalEngineError(_:)","role":"symbol","symbolKind":"case","modules":[{"name":"GnustoEngine"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","title":"ActionResponse.internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","url":"\/documentation\/gnustoengine","abstract":[],"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"title":"ActionResponse","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"url":"\/documentation\/gnustoengine\/actionresponse"}}}